[PythonPlugins]
GdalTools=true
db_manager=false
processing=true
MetaSearch=false
send2google_earth=true
StreetView=true
grassprovider=false
kmltools=true
SelectionFilter=true
latlontools=true
valuetool=true

#REPLACE {{}} WITH $ when issue will be closed https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/issues/769
[svg]
searchPathsForSVG=$SIG_RESOURCES_FOLDER\4_SYMBO\QGIS_SVG
[app]
projections\newProjectCrsBehavior=UsePresetCrs
projections\defaultProjectCrs=EPSG:2154
projections\unknownCrsBehavior=PromptUserForCrs

[Projections]
layerDefaultCrs=EPSG:2154
defaultBehavior=useProject

[PostgreSQL]
connections\Base%20carto\service=
connections\Base%20carto\host=51.91.102.175
connections\Base%20carto\port=5432
connections\Base%20carto\database=carto
connections\Base%20carto\username=
connections\Base%20carto\password=
connections\Base%20carto\authcfg=opale25
connections\Base%20carto\sslmode=SslDisable
connections\Base%20carto\publicOnly=false
connections\Base%20carto\geometryColumnsOnly=true
connections\Base%20carto\dontResolveType=false
connections\Base%20carto\allowGeometrylessTables=false
connections\Base%20carto\saveUsername=false
connections\Base%20carto\savePassword=false
connections\Base%20carto\estimatedMetadata=false
connections\Base%20carto\projectsInDatabase=false
connections\Base%20carto\metadataInDatabase=false
connections\Base%20carto\session_role=

[connections]
ows\items\wms\connections\items\Georisques\dpi-mode=7
ows\items\wms\connections\items\Georisques\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
ows\items\wms\connections\items\Georisques\ignore-axis-orientation=false
ows\items\wms\connections\items\Georisques\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\Georisques\ignore-get-map-uri=false
ows\items\wms\connections\items\Georisques\invert-axis-orientation=false
ows\items\wms\connections\items\Georisques\smooth-pixmap-transform=false
ows\items\wms\connections\items\Georisques\url=http://georisques.gouv.fr/services
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\smooth-pixmap-transform=true
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\url=https://data.geopf.fr/annexes/ressources/wms-r/orthohisto.xml
ows\items\wms\connections\items\IGN%20-%20Orthos\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Orthos\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Orthos\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Orthos\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Orthos\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Orthos\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Orthos\smooth-pixmap-transform=true
ows\items\wms\connections\items\IGN%20-%20Orthos\url=https://data.geopf.fr/annexes/ressources/wmts/ortho.xml
ows\items\wms\connections\items\IGN%20-%20Agriculture\authcfg=
ows\items\wms\connections\items\IGN%20-%20Agriculture\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Agriculture\feature-count=10
ows\items\wms\connections\items\IGN%20-%20Agriculture\http-header=@Variant(\0\0\0\b\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Agriculture\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\password=
ows\items\wms\connections\items\IGN%20-%20Agriculture\reported-layer-extents=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\smooth-pixmap-transform=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\tile-pixel-ratio=0
ows\items\wms\connections\items\IGN%20-%20Agriculture\url=https://data.geopf.fr/annexes/ressources/wmts/agriculture.xml
ows\items\wms\connections\items\IGN%20-%20Agriculture\username=
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\authcfg=
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\feature-count=10
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\http-header=@Variant(\0\0\0\b\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\password=
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\reported-layer-extents=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\smooth-pixmap-transform=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\tile-pixel-ratio=0
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\url=https://data.geopf.fr/annexes/ressources/wms-r/altimetrie.xml
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\username=
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\authcfg=
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\feature-count=10
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\http-header=@Variant(\0\0\0\b\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\password=
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\reported-layer-extents=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\smooth-pixmap-transform=true
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\tile-pixel-ratio=0
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\url=https://data.geopf.fr/annexes/ressources/wms-r/cartes.xml
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\username=
ows\items\wms\connections\items\IGN%20-%20Satellite\authcfg=
ows\items\wms\connections\items\IGN%20-%20Satellite\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Satellite\feature-count=10
ows\items\wms\connections\items\IGN%20-%20Satellite\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Satellite\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Satellite\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Satellite\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Satellite\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Satellite\password=
ows\items\wms\connections\items\IGN%20-%20Satellite\reported-layer-extents=false
ows\items\wms\connections\items\IGN%20-%20Satellite\smooth-pixmap-transform=false
ows\items\wms\connections\items\IGN%20-%20Satellite\tile-pixel-ratio=0
ows\items\wms\connections\items\IGN%20-%20Satellite\url=https://data.geopf.fr/annexes/ressources/wms-r/satellite.xml
ows\items\wms\connections\items\IGN%20-%20Satellite\username=