[PythonPlugins]
GdalTools=true
db_manager=false
processing=true
MetaSearch=false
send2google_earth=true
StreetView=true
sagaprovider=true
grassprovider=false
geometry_paster=true
ViewshedAnalysis=true
qfieldsync=true
Serval=true
kmltools=true
processing_saga_nextgen=true
SelectionFilter=true
SpreadsheetLayers=true
latlontools=true
valuetool=true
gpf_isochrone_isodistance_itineraire=true

[app]
projections\newProjectCrsBehavior=UsePresetCrs
projections\defaultProjectCrs=EPSG:2154
projections\unknownCrsBehavior=PromptUserForCrs
Windows\WelcomePage\SplitState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x4\x43\0\0\x2\t\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
Windows\WelcomePage\SplitState2=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xf0\0\0\0\xf0\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)

#REPLACE {{}} WITH $ when issue will be closed https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/issues/769
[core]
Layout\searchPathsForTemplates=$SIG_RESOURCES_FOLDER/5_MISES_EN_PAGE

[layout]
search-paths-for-templates=$SIG_RESOURCES_FOLDER/5_MISES_EN_PAGE

[svg]
searchPathsForSVG=$SIG_RESOURCES_FOLDER/4_SYMBO/QGIS_SVG

[Processing]
Configuration\SCRIPTS_FOLDERS=$SIG_RESOURCES_FOLDER/6_QGIS_SCRIPTS
Configuration\MODELS_FOLDER=$SIG_RESOURCES_FOLDER/6_QGIS_SCRIPTS

[UI]
Customization\enabled=true
state="@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x4\0\0\0\0\0\0\x1*\0\0\x3@\xfc\x2\0\0\0\xf\xfc\0\0\0\x95\0\0\x3@\0\0\0\x91\x1\0\0\x18\xfa\0\0\0\0\x1\0\0\0\x4\xfb\0\0\0\f\0L\0\x61\0y\0\x65\0r\0s\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x46\0\xff\xff\xff\xfb\0\0\0\f\0L\0\x65\0g\0\x65\0n\0\x64\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\xfb\0\0\0\x14\0L\0\x61\0y\0\x65\0r\0O\0r\0\x64\0\x65\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\x97\0\xff\xff\xff\xfb\0\0\0\xe\0\x42\0r\0o\0w\0s\0\x65\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x46\0\xff\xff\xff\xfb\0\0\0\x10\0O\0v\0\x65\0r\0v\0i\0\x65\0w\0\0\0\x1\xd7\0\0\0\xc4\0\0\0\x13\0\xff\xff\xff\xfb\0\0\0\"\0\x43\0o\0o\0r\0\x64\0i\0n\0\x61\0t\0\x65\0\x43\0\x61\0p\0t\0u\0r\0\x65\0\0\0\x1~\0\0\0\xa0\0\0\0\0\0\0\0\0\xfb\0\0\0\b\0U\0n\0\x64\0o\0\0\0\x1\xe4\0\0\0\xdc\0\0\0\0\0\0\0\0\xfb\0\0\0\x10\0\x42\0r\0o\0w\0s\0\x65\0r\0\x32\0\0\0\x2\x13\0\0\0\xad\0\0\0|\0\xff\xff\xff\xfb\0\0\0\x1c\0G\0P\0S\0I\0n\0\x66\0o\0r\0m\0\x61\0t\0i\0o\0n\0\0\0\x1\xbb\0\0\x1\x5\0\0\0]\0\xff\xff\xff\xfb\0\0\0(\0\x64\0w\0O\0p\0\x65\0n\0l\0\x61\0y\0\x65\0r\0s\0O\0v\0\x65\0r\0v\0i\0\x65\0w\0\0\0\x1\x64\0\0\x1\x37\0\0\0\0\0\0\0\0\xfb\0\0\0\x1c\0u\0n\0\x64\0o\0/\0r\0\x65\0\x64\0o\0 \0\x64\0o\0\x63\0k\0\0\0\0\0\xff\xff\xff\xff\0\0\0\xef\0\xff\xff\xff\xfb\0\0\0.\0\x41\0\x64\0v\0\x61\0n\0\x63\0\x65\0\x64\0\x44\0i\0g\0i\0t\0i\0z\0i\0n\0g\0T\0o\0o\0l\0s\0\0\0\0\0\xff\xff\xff\xff\0\0\0\xd8\0\xff\xff\xff\xfb\0\0\0\x34\0S\0t\0\x61\0t\0i\0s\0t\0\x61\0l\0S\0u\0m\0m\0\x61\0r\0y\0\x44\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\xfb\0\0\0&\0\x42\0o\0o\0k\0m\0\x61\0r\0k\0s\0\x44\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0x\0\xff\xff\xff\xfb\0\0\0\x38\0S\0t\0\x61\0t\0i\0s\0t\0i\0\x63\0\x61\0l\0S\0u\0m\0m\0\x61\0r\0y\0\x44\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0\xbe\0\xff\xff\xff\xfb\0\0\0\x18\0V\0\x65\0r\0t\0\x65\0x\0\x45\0\x64\0i\0t\0o\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0]\0\xff\xff\xff\xfb\0\0\0\x34\0Z\0o\0o\0m\0T\0o\0L\0\x61\0t\0L\0o\0n\0\x44\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\0\x42\0\x61\0s\0\x65\0\0\0\0\0\xff\xff\xff\xff\0\0\0l\0\0\0l\xfb\0\0\0\x14\0V\0\x61\0l\0u\0\x65\0 \0T\0o\0o\0l\0\0\0\x2\x12\0\0\x1\xc3\0\0\x1&\0\xff\xff\xff\0\0\0\x1\0\0\x1*\0\0\x2\x33\xfc\x2\0\0\0\x6\xfb\0\0\0\x1e\0S\0\x65\0x\0t\0\x61\0n\0t\0\x65\0T\0o\0o\0l\0\x62\0o\0x\0\0\0\0g\0\0\x2\x34\0\0\0\0\0\0\0\0\xfc\0\0\0\x64\0\0\x2\x33\0\0\0\0\0\xff\xff\xff\xfa\xff\xff\xff\xff\x1\0\0\0\x2\xfb\0\0\0\x18\0L\0\x61\0y\0\x65\0r\0S\0t\0y\0l\0i\0n\0g\0\0\0\x3\xd6\0\0\x1*\0\0\x1>\0\xff\xff\xff\xfb\0\0\0\"\0P\0r\0o\0\x63\0\x65\0s\0s\0i\0n\0g\0T\0o\0o\0l\0\x62\0o\0x\0\0\0\0\0\xff\xff\xff\xff\0\0\0\x46\0\xff\xff\xff\xfb\0\0\0\x14\0\x44\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\xfb\0\0\0\x10\0\x44\0\x65\0v\0T\0o\0o\0l\0s\0\0\0\0\0\xff\xff\xff\xff\0\0\0]\0\xff\xff\xff\xfb\0\0\0\x1a\0R\0\x65\0s\0u\0l\0t\0s\0V\0i\0\x65\0w\0\x65\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\x1\x1d\0\xff\xff\xff\xfb\0\0\0 \0t\0h\0\x65\0T\0i\0l\0\x65\0S\0\x63\0\x61\0l\0\x65\0\x44\0o\0\x63\0k\0\0\0\0\0\xff\xff\xff\xff\0\0\0\x8d\0\xff\xff\xff\0\0\0\x2\0\0\0\0\0\0\0\0\xfc\x1\0\0\0\x1\xfb\0\0\0&\0T\0\x65\0m\0p\0o\0r\0\x61\0l\0 \0\x43\0o\0n\0t\0r\0o\0l\0l\0\x65\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\x2\xa7\0\xff\xff\xff\0\0\0\x3\0\0\x3\xac\0\0\x1\x65\xfc\x1\0\0\0\x3\xfb\0\0\0\x14\0M\0\x65\0s\0s\0\x61\0g\0\x65\0L\0o\0g\0\0\0\x1T\0\0\x3\xac\0\0\0\x7f\0\xff\xff\xff\xfb\0\0\0&\0U\0s\0\x65\0r\0I\0n\0p\0u\0t\0\x44\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\x2\0\0\0\0\0\0\0\0\0\0\0\xc8\0\0\0\x64\xfb\0\0\0\x1a\0P\0y\0t\0h\0o\0n\0\x43\0o\0n\0s\0o\0l\0\x65\x1\0\0\x1O\0\0\x5\xaf\0\0\0\0\0\0\0\0\0\0\x6P\0\0\x3@\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x2\xfc\0\0\0\r\0\0\0\0\0\0\0\x1\0\0\0\x1a\0m\0L\0\x61\0y\0\x65\0r\0T\0o\0o\0l\0\x42\0\x61\0r\x2\0\0\0\xc2\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x2\0\0\0\0\0\0\0\x2\0\0\0\0\0\0\0\x2\0\0\0\x4\0\0\0\x18\0m\0\x46\0i\0l\0\x65\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1c\0m\0M\0\x61\0p\0N\0\x61\0v\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\xd6\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\"\0m\0S\0\x65\0l\0\x65\0\x63\0t\0i\0o\0n\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x2\xf6\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0$\0m\0\x41\0t\0t\0r\0i\0\x62\0u\0t\0\x65\0s\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x3\xba\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x2\0\0\0\0\0\0\0\x2\0\0\0\0\0\0\0\x2\0\0\0\0\0\0\0\x2\0\0\0\0\0\0\0\x2\0\0\0\0\0\0\0\x2\0\0\0\b\0\0\0\x32\0m\0\x44\0\x61\0t\0\x61\0S\0o\0u\0r\0\x63\0\x65\0M\0\x61\0n\0\x61\0g\0\x65\0r\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0 \0m\0\x44\0i\0g\0i\0t\0i\0z\0\x65\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\xf7\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1a\0m\0L\0\x61\0\x62\0\x65\0l\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x2\xed\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0 \0m\0\x44\0\x61\0t\0\x61\0\x62\0\x61\0s\0\x65\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\x2o\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x16\0m\0W\0\x65\0\x62\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\x4*\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x18\0m\0H\0\x65\0l\0p\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\x4;\0\0\0\xcf\0\0\0\0\0\0\0\0\0\0\0\x1c\0m\0V\0\x65\0\x63\0t\0o\0r\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\x4;\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0 \0m\0S\0n\0\x61\0p\0p\0i\0n\0g\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x4\x34\0\0\x2[\0\0\0\0\0\0\0\0\0\0\0\x2\0\0\0\x2\0\0\0\x30\0m\0\x41\0\x64\0v\0\x61\0n\0\x63\0\x65\0\x64\0\x44\0i\0g\0i\0t\0i\0z\0\x65\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1c\0m\0R\0\x61\0s\0t\0\x65\0r\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\0\0\0\0\x2\xb0\0\0\0\0\0\0\0\0\0\0\0\x2\0\0\0\n\0\0\0*\0m\0S\0h\0\x61\0p\0\x65\0\x44\0i\0g\0i\0t\0i\0z\0\x65\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x18\0m\0M\0\x65\0s\0h\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\0\xb8\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0&\0m\0\x41\0n\0n\0o\0t\0\x61\0t\0i\0o\0n\0s\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\0\xb8\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x16\0m\0G\0p\0s\0T\0o\0o\0l\0\x42\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\x2M\ba\0'\x81\xd7\0\0\0\x1e\0K\0M\0L\0T\0o\0o\0l\0s\0T\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0$\0L\0\x61\0t\0L\0o\0n\0T\0o\0o\0l\0s\0T\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\xb5\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0$\0Q\0\x46\0i\0\x65\0l\0\x64\0S\0y\0n\0\x63\0 \0T\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\x1\xd9\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0&\0S\0\x65\0r\0v\0\x61\0l\0 \0M\0\x61\0i\0n\0 \0T\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\x2\x95\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x30\0S\0\x65\0r\0v\0\x61\0l\0 \0S\0\x65\0l\0\x65\0\x63\0t\0i\0o\0n\0 \0T\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\x4\xc0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1c\0m\0P\0l\0u\0g\0i\0n\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x6-\0\0\x1S\0\0\0\0\0\0\0\0)"
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xff\xff\xff\xff\xf8\0\0\a\x80\0\0\x4\b\0\0\0\x1\0\0\0\x1f\0\0\x4H\0\0\x2\xf1\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\x17\0\0\a\x7f\0\0\x4\a)

[Projections]
layerDefaultCrs=EPSG:2154
defaultBehavior=useProject

[PostgreSQL]
connections\Base%20carto\service=
connections\Base%20carto\host=51.91.102.175
connections\Base%20carto\port=5432
connections\Base%20carto\database=carto
connections\Base%20carto\username=
connections\Base%20carto\password=
connections\Base%20carto\authcfg=opale25
connections\Base%20carto\sslmode=SslDisable
connections\Base%20carto\publicOnly=false
connections\Base%20carto\geometryColumnsOnly=true
connections\Base%20carto\dontResolveType=false
connections\Base%20carto\allowGeometrylessTables=false
connections\Base%20carto\saveUsername=false
connections\Base%20carto\savePassword=false
connections\Base%20carto\estimatedMetadata=false
connections\Base%20carto\projectsInDatabase=false
connections\Base%20carto\metadataInDatabase=false
connections\Base%20carto\session_role=

[connections]
ows\items\wms\connections\items\Georisques\dpi-mode=7
ows\items\wms\connections\items\Georisques\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
ows\items\wms\connections\items\Georisques\ignore-axis-orientation=false
ows\items\wms\connections\items\Georisques\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\Georisques\ignore-get-map-uri=false
ows\items\wms\connections\items\Georisques\invert-axis-orientation=false
ows\items\wms\connections\items\Georisques\smooth-pixmap-transform=false
ows\items\wms\connections\items\Georisques\url=http://georisques.gouv.fr/services
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\smooth-pixmap-transform=true
ows\items\wms\connections\items\IGN%20-%20Orthos%20historiques\url=https://data.geopf.fr/annexes/ressources/wms-r/orthohisto.xml
ows\items\wms\connections\items\IGN%20-%20Orthos\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Orthos\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Orthos\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Orthos\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Orthos\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Orthos\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Orthos\smooth-pixmap-transform=true
ows\items\wms\connections\items\IGN%20-%20Orthos\url=https://data.geopf.fr/annexes/ressources/wmts/ortho.xml
ows\items\wms\connections\items\IGN%20-%20Agriculture\authcfg=
ows\items\wms\connections\items\IGN%20-%20Agriculture\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Agriculture\feature-count=10
ows\items\wms\connections\items\IGN%20-%20Agriculture\http-header=@Variant(\0\0\0\b\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Agriculture\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\password=
ows\items\wms\connections\items\IGN%20-%20Agriculture\reported-layer-extents=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\smooth-pixmap-transform=false
ows\items\wms\connections\items\IGN%20-%20Agriculture\tile-pixel-ratio=0
ows\items\wms\connections\items\IGN%20-%20Agriculture\url=https://data.geopf.fr/annexes/ressources/wmts/agriculture.xml
ows\items\wms\connections\items\IGN%20-%20Agriculture\username=
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\authcfg=
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\feature-count=10
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\http-header=@Variant(\0\0\0\b\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\password=
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\reported-layer-extents=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\smooth-pixmap-transform=false
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\tile-pixel-ratio=0
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\url=https://data.geopf.fr/annexes/ressources/wms-r/altimetrie.xml
ows\items\wms\connections\items\IGN%20-%20Altim%E9trie\username=
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\authcfg=
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\feature-count=10
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\http-header=@Variant(\0\0\0\b\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\password=
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\reported-layer-extents=false
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\smooth-pixmap-transform=true
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\tile-pixel-ratio=0
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\url=https://data.geopf.fr/annexes/ressources/wms-r/cartes.xml
ows\items\wms\connections\items\IGN%20-%20Cartes%20L93\username=
ows\items\wms\connections\items\IGN%20-%20Satellite\authcfg=
ows\items\wms\connections\items\IGN%20-%20Satellite\dpi-mode=7
ows\items\wms\connections\items\IGN%20-%20Satellite\feature-count=10
ows\items\wms\connections\items\IGN%20-%20Satellite\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
ows\items\wms\connections\items\IGN%20-%20Satellite\ignore-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Satellite\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\IGN%20-%20Satellite\ignore-get-map-uri=false
ows\items\wms\connections\items\IGN%20-%20Satellite\invert-axis-orientation=false
ows\items\wms\connections\items\IGN%20-%20Satellite\password=
ows\items\wms\connections\items\IGN%20-%20Satellite\reported-layer-extents=false
ows\items\wms\connections\items\IGN%20-%20Satellite\smooth-pixmap-transform=false
ows\items\wms\connections\items\IGN%20-%20Satellite\tile-pixel-ratio=0
ows\items\wms\connections\items\IGN%20-%20Satellite\url=https://data.geopf.fr/annexes/ressources/wms-r/satellite.xml
ows\items\wms\connections\items\IGN%20-%20Satellite\username=